/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as EvalsRouteImport } from './routes/evals'
import { Route as BackgroundAgentsRouteImport } from './routes/background-agents'
import { Route as IndexRouteImport } from './routes/index'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/skills.lazy').then((d) => d.Route))
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/memory.lazy').then((d) => d.Route))
const EvalsRoute = EvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/evals.lazy').then((d) => d.Route))
const BackgroundAgentsRoute = BackgroundAgentsRouteImport.update({
  id: '/background-agents',
  path: '/background-agents',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/background-agents.lazy').then((d) => d.Route),
)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/background-agents': typeof BackgroundAgentsRoute
  '/evals': typeof EvalsRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/background-agents': typeof BackgroundAgentsRoute
  '/evals': typeof EvalsRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/background-agents': typeof BackgroundAgentsRoute
  '/evals': typeof EvalsRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/background-agents'
    | '/evals'
    | '/memory'
    | '/settings'
    | '/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/background-agents'
    | '/evals'
    | '/memory'
    | '/settings'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/background-agents'
    | '/evals'
    | '/memory'
    | '/settings'
    | '/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackgroundAgentsRoute: typeof BackgroundAgentsRoute
  EvalsRoute: typeof EvalsRoute
  MemoryRoute: typeof MemoryRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evals': {
      id: '/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof EvalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background-agents': {
      id: '/background-agents'
      path: '/background-agents'
      fullPath: '/background-agents'
      preLoaderRoute: typeof BackgroundAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackgroundAgentsRoute: BackgroundAgentsRoute,
  EvalsRoute: EvalsRoute,
  MemoryRoute: MemoryRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
