const timestamp = '2026-06-17T00:00:00.000Z'
const toolErrorWithheldMessage = 'Tool error withheld from conversation timeline.'
const runModelSnapshot = {
  modelConfigId: 'provider-config-001',
  providerId: 'openai',
  modelId: 'gpt-4.1',
  displayName: 'GPT-4.1',
  protocol: 'responses',
}

export const runEventFixtures: Array<Record<string, unknown>> = [
  {
    id: 'evt-001',
    runId: 'run-001',
    sequence: 1,
    timestamp,
    type: 'run.started',
    source: 'engine',
    visibility: 'public',
    payload: { sessionId: 'session-001', model: runModelSnapshot },
  },
  {
    id: 'evt-002',
    runId: 'run-001',
    sequence: 2,
    timestamp,
    type: 'run.ended',
    source: 'engine',
    visibility: 'public',
    payload: { reason: 'completed' },
  },
  {
    id: 'evt-003',
    runId: 'run-001',
    sequence: 3,
    timestamp,
    type: 'assistant.delta',
    source: 'assistant',
    visibility: 'public',
    payload: { messageId: 'msg-001', text: 'Hello' },
  },
  {
    id: 'evt-004',
    runId: 'run-001',
    sequence: 4,
    timestamp,
    type: 'assistant.completed',
    source: 'assistant',
    visibility: 'public',
    payload: { messageId: 'msg-001' },
  },
  {
    id: 'evt-005',
    runId: 'run-001',
    sequence: 5,
    timestamp,
    type: 'tool.requested',
    source: 'tool',
    visibility: 'redacted',
    payload: { toolUseId: 'tool-001', toolName: 'read' },
  },
  {
    id: 'evt-006',
    runId: 'run-001',
    sequence: 6,
    timestamp,
    type: 'tool.approved',
    source: 'tool',
    visibility: 'public',
    payload: { toolUseId: 'tool-001' },
  },
  {
    id: 'evt-007',
    runId: 'run-001',
    sequence: 7,
    timestamp,
    type: 'tool.denied',
    source: 'tool',
    visibility: 'public',
    payload: { toolUseId: 'tool-002' },
  },
  {
    id: 'evt-008',
    runId: 'run-001',
    sequence: 8,
    timestamp,
    type: 'tool.completed',
    source: 'tool',
    visibility: 'redacted',
    payload: { toolUseId: 'tool-001', durationMs: 42 },
  },
  {
    id: 'evt-009',
    runId: 'run-001',
    sequence: 9,
    timestamp,
    type: 'tool.failed',
    source: 'tool',
    visibility: 'redacted',
    payload: {
      toolUseId: 'tool-003',
      code: 'tool_error',
      message: toolErrorWithheldMessage,
    },
  },
  {
    id: 'evt-010',
    runId: 'run-001',
    sequence: 10,
    timestamp,
    type: 'permission.requested',
    source: 'policy',
    visibility: 'public',
    payload: {
      actorSource: { type: 'parentRun' },
      actionPlanHash: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      autoResolved: false,
      decisionScope: 'current run',
      effectiveMode: 'default',
      exposure: 'Can run inside the local workspace boundary.',
      operation: 'Review permission',
      reason: 'The runtime requires a human permission decision.',
      review: {
        confirmation: { type: 'none' },
        details: [],
        redacted: true,
        summary: 'Permission review unavailable.',
      },
      requestId: '01HZ0000000000000000000001',
      sandboxPolicy: {
        mode: { osLevel: 'none' },
        network: 'none',
        resourceLimits: {
          maxCpuCores: null,
          maxMemoryBytes: null,
          maxOpenFiles: null,
          maxPids: null,
          maxWallClockMs: null,
        },
        scope: 'workspace_only',
      },
      severity: 'medium',
      target: 'local workspace',
      toolUseId: 'tool-001',
      workspaceBoundary: 'workspace://local',
    },
  },
  {
    id: 'evt-011',
    runId: 'run-001',
    sequence: 11,
    timestamp,
    type: 'permission.resolved',
    source: 'policy',
    visibility: 'public',
    payload: {
      actionPlanHash: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      autoResolved: false,
      decision: 'approve',
      decisionId: 'decision-001',
      requestId: '01HZ0000000000000000000001',
    },
  },
  {
    id: 'evt-012',
    runId: 'run-001',
    sequence: 12,
    timestamp,
    type: 'artifact.created',
    source: 'engine',
    visibility: 'public',
    payload: { artifactId: 'artifact-001', status: 'ready' },
  },
  {
    id: 'evt-013',
    runId: 'run-001',
    sequence: 13,
    timestamp,
    type: 'artifact.updated',
    source: 'engine',
    visibility: 'public',
    payload: { artifactId: 'artifact-001', status: 'running' },
  },
  {
    id: 'evt-014',
    runId: 'run-001',
    sequence: 14,
    timestamp,
    type: 'assistant.review.requested',
    source: 'assistant',
    visibility: 'public',
    payload: {
      requestId: '01HZ0000000000000000000001',
      title: 'Review changes',
      body: 'Confirm before applying.',
    },
  },
  {
    id: 'evt-015',
    runId: 'run-001',
    sequence: 15,
    timestamp,
    type: 'assistant.clarification.requested',
    source: 'assistant',
    visibility: 'public',
    payload: {
      requestId: '01HZ0000000000000000000002',
      prompt: 'Which style should I use?',
    },
  },
  {
    id: 'evt-016',
    runId: 'run-001',
    sequence: 16,
    timestamp,
    type: 'assistant.notice',
    source: 'assistant',
    visibility: 'public',
    payload: {
      noticeId: '01HZ0000000000000000000003',
      body: 'Tool output was summarized.',
    },
  },
  {
    id: 'evt-017',
    runId: 'run-001',
    sequence: 17,
    timestamp,
    type: 'engine.failed',
    source: 'engine',
    visibility: 'public',
    payload: { message: 'model stream failed' },
  },
].map((event, index) => ({ conversationSequence: index + 1, ...event }))
